import '../../src/widgets/nav-bar.test'
import '../../src/features/playlist/playlist.test'
import '../../src/features/playlist/song.test'
import '../../src/features/playlist/reducers.test'
import '../../src/features/discover/reducers.test'
